export const userCSSSelectors = {
  'wrapper': 'lyrs-usercss-wrapper',
  'wrapper--stopped': 'lyrs-usercss-wrapper--stopped',
  'wrapper--idle': 'lyrs-usercss-wrapper--idle',
  'wrapper--playing': 'lyrs-usercss-wrapper--playing',
  'wrapper--hover': 'lyrs-usercss-wrapper--hover',
  'alert': 'lyrs-usercss-alert',
  'alert--disconnected': 'lyrs-usercss-alert--disconnected',
  'alert--description': 'lyrs-usercss-alert--description',
  'lyrics-item': 'lyrs-usercss-lyrics-item',
  'lyrics': 'lyrs-usercss-lyrics',
  'lyrics-wrapper': 'lyrs-usercss-lyrics-wrapper',
  'lyrics-wrapper--previous': 'lyrs-usercss-lyrics-wrapper--previous',
  'lyrics-wrapper--current': 'lyrs-usercss-lyrics-wrapper--current',
  'lyrics-wrapper--next': 'lyrs-usercss-lyrics-wrapper--next',
  'lyrics-transition-wrapper': 'lyrs-usercss-lyrics-transition-wrapper',
  'lyrics-container': 'lyrs-usercss-lyrics-container',
  'nowplaying': 'lyrs-usercss-nowplaying',
  'nowplaying-progress': 'lyrs-usercss-nowplaying-progress',
  'nowplaying-progress-bar': 'lyrs-usercss-nowplaying-progress-bar',
  'nowplaying-container': 'lyrs-usercss-nowplaying-container',
  'nowplaying-cover': 'lyrs-usercss-nowplaying-cover',
  'nowplaying-cover--empty': 'lyrs-usercss-nowplaying-cover--empty',
  'nowplaying-playing-text': 'lyrs-usercss-playing-text',
  'nowplaying-marquee': 'lyrs-usercss-nowplaying-marquee',
  'nowplaying-title': 'lyrs-usercss-nowplaying-title',
  'nowplaying-divider': 'lyrs-usercss-nowplaying-divider',
  'nowplaying-artist': 'lyrs-usercss-nowplaying-artist',
  'marquee': 'lyrs-usercss-marquee',
  'marquee--disabled': 'lyrs-usercss-marquee--disabled',
};

export const userCSSTransitions = {
  'transition-lyric': 'lyric-custom',
};

export const userCSSVariables = {
  'var-proximity-opacity': '--proximity',
  'var-cover-url': '--cover-url',
  'var-nowplaying-percent': '--nowplaying-percent',
  'var-nowplaying-duration': '--nowplaying-duration',
  'var-nowplaying-progress': '--nowplaying-progress',
  'var-lyric-order': '--lyric-order',
  'var-lyric-order-offset': '--lyric-order-offset',
};
